import React from 'react'
import Head from 'next/head'

export default function AppHead() {
  return (
    <Head>
      <title>Wimo Application</title>
      <meta name="viewport" content="initial-scale=1.0, width=device-width"></meta>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'></link>
      <link 
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
        rel="stylesheet" 
        crossOrigin="anonymous"/>

      <script
        src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"></script>
      <script
        src="https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js"></script>
    </Head>
  )
}